Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "ebpf" do |machine|
      machine.vm.hostname = "ebpf"
   end
end
